### ISSUE TITLE
How to show the software version number?

### ISSUE THREAD

**Issue by chansters** [denverquane/MMM-Teslamate#23]
First of all, thanks for building this module, it's working great ! I'm trying to edit your module to show the software version below the odometer reading.  I can get it to display most the values from MQTT except for version.  It shows up as "0".  Would appreciate any guidance to get this to work.  Thanks!!

![telegram](https://user-images.githubusercontent.com/8441205/103423466-90e58480-4b5b-11eb-9ce2-352f4ae709f1.png)

My modified JS file : https://pastebin.com/zmcHKM34

**Comment by olexs** [comment]
You need to add the subscription to the `/version` topic in `node_helper.js` as well as in the main file. `node_helper.js` is what runs on the "server" side of MagicMirror and actually fetches data from Teslamate, while the `MMM-Teslamate.js` file is executed in the browser frontend.

**Comment by chansters** [comment]
> You need to add the subscription to the `/version` topic in `node_helper.js` as well as in the main file. `node_helper.js` is what runs on the "server" side of MagicMirror and actually fetches data from Teslamate, while the `MMM-Teslamate.js` file is executed in the browser frontend.

Thank you !! That did the trick.  Thanks for explaining the role of the node_helper.js file.  I'm a week old with MM and I had no idea that was the purpose of this file.
