### ISSUE TITLE
Connection doesn't work if port is different than default 1883

### ISSUE THREAD

**Issue by greenmansuperhero** [denverquane/MMM-Teslamate#31]
Hey,
I've tried to connect to my MQTT server and it failed due to connection issue.

The problem here is that the single pipe operator, if the port is specified, in fact is doing a bitwise operation during string concatenation.
I would change it with the coalesce operator "??" instead:

https://github.com/denverquane/MMM-Teslamate/blob/183a3715f5b0017bee3a7e0a43563b9be4cc1eaf/MMM-Teslamate.js#L30

This has to be changed also in node_helper file.

Hope this helps.

**Comment by denverquane** [comment]
Fixed, appreciate the heads up
