### ISSUE TITLE
Data Not Populating

### ISSUE THREAD

**Issue by solelo** [denverquane/MMM-Teslamate#34]
Teslamate seems to working great but the module doesn't seem to be populating for some reason. The module connects to the port but still no data on the module being populated. Any suggestion?

**Comment by olexs** [comment]
Any logs from MagicMirror or the browser?

Check the following:
- ran `npm install` (or preferrably `npm ci`) in the module folder after installation?
- ensured MQTT is enabled in Teslamate?

Also please attach your module configuration, of course without any passwords or other identifying data.

**Comment by solelo** [comment]
` module: 'MMM-Teslamate',
    position: 'bottom_right',
    config: {
        mqttServer: {
            address: 'REDACTED',  // Server address or IP address of the MQTT broker
            port: 1883,              // Port number if other than default (1883)
            //user: 'user',          // Leave out for no user
            //password: 'password',  // Leave out for no password
				},

        rangeDisplay: "%", // "%" or "range"
        imperial: true, //use imperial units (true = Miles & F) or metric (false = Km & C)

        carID: '1', // defaults to '1'; only override if you have multiple Teslas and want to display 
                    // a specific car per instance of the module

        // set to true to enable both the graphic, and the additional stats 
        // (charge remaining, scheduled charge start, etc)
        hybridView: true,
        // size of the visible area
        sizeOptions: {
            // size of the icons + battery (above text)
            width: 450, // px, default: 450
            height: 203, // px, default: 203
            // the battery images itself
            batWitdh: 250, // px, default: 250
            batHeight: 75, // px, default: 75
            // visual distance reduction to the module above
            topOffset: -40, // px, default: -40
					},
        carImageOptions: {
            model: "my", // mx, ms (S pre-refresh), ? (S post-refresh)

            view: "STUD_3QTR", // STUD_SIDE works better for S/X

            // full list of option codes: https://tesla-api.timdorr.com/vehicle/optioncodes.
            // you need at least the color and the wheels. not all combos work.
            // also consult: https://teslaownersonline.com/threads/teslas-image-compositor.7089/
            options: "MTY09,WY20P,PPSW,SLR1,INBPW",

            // play with this until it looks about right.
            // tested values: 0 for m3/STUD_3QTR, 25 for ms/STUD_SIDE
            verticalOffset: 0,

            opacity: 0.5
						},

        // show inside and outside temperatures below the car image: when AC or preconditioning is running (default), always, or never
        showTemps: "hvac_on", // "always", "never"
						}
	`

**Comment by solelo** [comment]
How do I validate that MQTT is enable in Teslamate? I saw the ports commented out in the setup and have attempted to uncomment it out but then the web interface doesn't work.

**Comment by olexs** [comment]
Depends on how you run Teslamate. Can you link the guide / base configuration you followed, or describe the setup?

**Comment by solelo** [comment]
I used this guide [Teslamate](https://docs.teslamate.org/docs/installation/docker/)

**Comment by solelo** [comment]
Also; is there a way to move the battery icon below the car? Or should I just attempt a custom css?

**Comment by olexs** [comment]
Yeah, if you run that you need to uncomment the ports for `mosquitto`. Make sure the indentation is exactly correct - check vs the other ports definitions in the file and match it exactly space-for-space, YAML is nitpicky about it.

**Comment by solelo** [comment]
`      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
     ports:
       - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

`

**Comment by solelo** [comment]
This is what I have and it seems to break the entire Teslamate

**Comment by olexs** [comment]
Can you run `docker-compose logs` after trying to run the setup with the ports enabled, and see if there's any errors in there?

Do you run some other software on the same machine as Teslamate that may be using the 1883 port already?

**Comment by solelo** [comment]
<img width="585" alt="Screen Shot 2022-06-04 at 14 35 26" src="https://user-images.githubusercontent.com/40755037/172021124-87279236-e493-4bf2-88a0-35bb5c619211.png">

**Comment by solelo** [comment]
There are no other softwares running, I'm also on Teslamate 1.25.0 because it errors out on "latest," I'm not sure if that matters

**Comment by olexs** [comment]
Hmm. It looks like your `docker-compose.yml` is not right after enabling the 1883:1883 line, and unfortunately the indentation is lost when you paste code here on Github. Can you post a screenshot of the `mosquitto` block, or upload the whole file somewhere and link it here (again, ofc without passwords or other identifying info)?

**Comment by solelo** [comment]
<img width="1206" alt="Screen Shot 2022-06-04 at 14 40 57" src="https://user-images.githubusercontent.com/40755037/172021364-aad781c7-c552-4e67-9f05-b5197d983884.png">

**Comment by solelo** [comment]
I feel like it's pretty spot on, I've counted all the spaces

**Comment by olexs** [comment]
Yeah, indentation is the issue. `ports` needs to be exactly aligned with `command` above it, and `- 1883:1883` needs to match the line two below it (`mosquitto-conf:/...`). Also make sure it's all indented with spaces and not tabs.

**Comment by solelo** [comment]
<img width="1613" alt="Screen Shot 2022-06-04 at 14 48 38" src="https://user-images.githubusercontent.com/40755037/172021518-5de2daec-3acd-4db9-8cba-0b7e42fd1ff8.png">

Ok so that worked now there is another error.. <facepalm>

**Comment by olexs** [comment]
Have you ran `docker-compose down` before restarting it all, if it's been running already before? This now says that port 1883 is in use by something, and if you say you're not running anything else on the Raspi, then it's probably an old instance of mosquitto from this very config that has been running since one of the earlier attempts.

**Comment by solelo** [comment]
<img width="1613" alt="Screen Shot 2022-06-04 at 14 55 51" src="https://user-images.githubusercontent.com/40755037/172021781-86d3fee0-4d8e-48a4-9bdd-6474392ddade.png">

There doesn't seem to be anything else on it that should be stopped

**Comment by solelo** [comment]
Do you think it would help to uninstall MQTT and reinstall it all the way from scratch?

**Comment by olexs** [comment]
That's very weird. I'd try `docker-compose down`, then restart the whole Pi, and try to start it up again. 

If that still doesn't work, the only explanation is something is indeed blocking the port. You could work around that by using a different port though, for example changing the line in `docker-compose.yml` to ` - 1884:1883`, and then when it starts up without errors configure MMM-Teslamate to port 1884 instead of 1883 too, no reason why that shouldn't work.

... wait, you have installed MQTT separately on the Raspberry? You don't need that, and that would probably be what is interfering with the ports then. If you don't use it for anything else, uninstall it, the Docker container in the Teslamate `docker-compose.yml` is all you need.

**Comment by solelo** [comment]
*Facepalms* I just removed it and it is not giving errors. I'l check and see if it's populating on the module now. Thanks a lot for you help I really appreciate. Last question is there a way to move the batter form overlaying on the car?

**Comment by olexs** [comment]
You're welcome, always glad to help a fellow Tesla driver and MagicMirror user, we're few and far between :)

There's no intended way to move the battery off of the car, unfortunately. I designed the layout to match the way it was a while back in the phone app, -ish. You could play around with the size and offset parameters in the config, and if that doesn't help, either run custom CSS or poke at the layout code in `MMM-Teslamate.js` (lines 399+).

**Comment by solelo** [comment]
We are very few and far between! Hopefully more people hop on board at some point. I do appreciate the help and well the module is great!

I'll mess around with the code some to set it up for my liking as best as I can.
Thanks again for the help!
