### ISSUE TITLE
Support multiple cars

### ISSUE THREAD

**Issue by pwestbro** [denverquane/MMM-Teslamate#9]
I am not able to see how to configure multiple cars in MMM-Teslamate.

My Teslamate is importing data from each of our cars.  Is there a way to configure MMM-Teslamate to show data from each of these?

**Comment by denverquane** [comment]
Right now it isn't supported, but thanks for letting me know you'd like to see this functionality! I don't foresee it being a difficult feature to add; I think the easiest path forward would be to have two separate instances of the module on the mirror, with config that just specifies which of the cars should be displayed. But right now that functionality isn't supported.

I'll probably work on this soon and get back to you!  :)

**Comment by denverquane** [comment]
> I am not able to see how to configure multiple cars in MMM-Teslamate.
> 
> My Teslamate is importing data from each of our cars. Is there a way to configure MMM-Teslamate to show data from each of these?

Just pushed a change that allows this functionality! Now you can set the `carID` attribute in config (see the `README.md` for an example), and have multiple copies of the MMM-Teslamate module, with each instance using the relevant config for that specific car.

If you wouldn't mind letting me know if this commit works for you - I don't have an easy way to fully test locally - I'd really appreciate it 😄

**Comment by pwestbro** [comment]
Thank you.  This is working well for me.

![20200405_172847](https://user-images.githubusercontent.com/22271817/78513865-559c5d80-7763-11ea-9e98-93540d86530b.jpg)
